### ISSUE TITLE
bugfix -- label width

### ISSUE THREAD

**Issue by mtill** [iVis-at-Bilkent/cytoscape-chola.js#1]
nodeDimensionsIncludeLabels: true

... does not work. Fix:

change line 1901 from ...
var createClasslabelWidth = theChild.boundingBox({ includeLabels: true, includeNodes: false }).w;
... to:
var labelWidth = theChild.boundingBox({ includeLabels: true, includeNodes: false }).w;

Best regards

**Comment by MobiZaman** [comment]
The issue has been fixed in the unstable branch.
